### ISSUE TITLE
ServicePulse angular pages links are broken on ServicePulse version 1.34.4 and  1.35.0

### ISSUE THREAD

**Issue by soujay** [Particular/Particular.PlatformSample#290]
#### Description

When the [servicepulse version](https://github.com/Particular/Particular.PlatformSample/blob/c9171eaf3e3b35c7b935e74141f270a88f749f5a/src/Particular.PlatformSample/Particular.PlatformSample.csproj#L17) is updated in the [csproj](https://github.com/Particular/Particular.PlatformSample/blob/master/src/Particular.PlatformSample/Particular.PlatformSample.csproj) file to version higher than 1.33.1 (eg:,1.34.4or 1.35.0) the angular pages links are broken. The Urls that point to the angular pages have 'undefined' in the route

#### Expected behavior
The angular pages should continue to resolve and  load as before

#### Actual behavior
The angular pages does not load and the urls have a "/undefineda" in them that causes it to break

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        
Particular.PlatformSample.ServicePulse 1.34.4
Particular.PlatformSample.ServicePulse 1.35.0

### Steps to reproduce

1. Clone and checkout  the [Particular.PlatformSample repo](https://github.com/Particular/Particular.PlatformSample/tree/master)
2. Update the [Particular.PlatformSample.ServicePulse version](https://github.com/Particular/Particular.PlatformSample/blob/c9171eaf3e3b35c7b935e74141f270a88f749f5a/src/Particular.PlatformSample/Particular.PlatformSample.csproj#L17) in the csproj file to either version 1.34.4 or 1.35.0
3. Run the smoketest project
4. The dashboard is opened in the web browser. http://localhost:49205/#/dashboard
5. Ensure to hard refresh by using Ctrl+Shift+R
6. Navigate to an angular page that has not yet been converted to vue
   Eg: Heartbeats, monitoring, custom checks or Events
   
![image](https://user-images.githubusercontent.com/88632084/229829318-275c0179-240a-4764-ad9e-1881a7adb249.png)

7. The angular pages do not load and have an incorrect url. Eg:
   - http://localhost:49205/undefineda/#/endpoints
   - http://localhost:49205/undefineda/#/monitoring
   - http://localhost:49205/undefineda/#/custom-checks
   - http://localhost:49205/undefineda/#/events

### Additional Information

This issue is not observed when using ServicePulse directly. Only when started by the Platform sample. 

Browser caching plays an important role here. Ensure to refresh the browser with a hard-refresh while reproducing and testing between different versions.

Since the [latest version of PlatformSample 2.28.0](https://www.nuget.org/packages/Particular.PlatformSample/2.28.0)e uses ServicePulse 1.35.0, the [latest version of monitoring demo](https://github.com/Particular/MonitoringDemo/blob/master/src/Platform/Platform.csproj#L13) uses this version of PlatformSample. Hence the monitoring demo also has the incorrect angular urls

#### Workarounds
There are a couple of workarounds,

1.  Use only the versions   1.33.1 or below of servicepulse in PlatformSample. If using the monitoring demo, continue to use the order versions and avoid using the latest version.
2. Manually fix the broken link by removing the "undefined" word from the url. 
   Eg: Incorrect Url: http://localhost:49205/undefineda/#/endpoints
    Corrected Url:  http://localhost:49205/a/#/endpoints

**Comment by tmasternak** [comment]
This has been fixed in https://github.com/Particular/Particular.PlatformSample/releases/tag/2.32.0 release.
