### ISSUE TITLE
Cannot Expose RavenDB

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/Particular.PlatformSample#5]
When I ran the smoke test on my machine it fails with an "access denied" error message. After some digging around it appears that my machine had an old registry setting that caused ServiceControl to set the ExposeRavenDB setting to true. SC reads missing config file values from the registry ([see here](https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Infrastructure/Settings/SettingsReader.cs#L17)).

@danielmarbach already fixed this by explicitly adding ExposeRavenDB=false to the config file.

After some deeper digging I found that when Raven exposes it's internal http server it passes in a strong wildcard: [Here's the code](https://github.com/ravendb/ravendb/blob/v3.5/Raven.Database/Server/OwinHttpServer.cs#L43)

We aren't testing for that, or adding a URLACL or anything. The result is that the when we try and register a listener with http.sys, it blows up because the Strong Wildcard binding requires a URLACL and I don't have one set up for it.

**Comment by bording** [comment]
Why would we need to be able to do that for the sample package?

**Comment by mikeminutillo** [comment]
Only for debugging purposes if something goes wrong with a demo or something. It's not a high prio to fix it. If the behavior of SC was to change to always expose RavenDB then it would break this package.

**Comment by DavidBoike** [comment]
With PlatformSample 3.x using ServiceControl 5 and RavenDB 5, you can't _not_ expose RavenDB, so I'm closing this issue.
